#!/usr/bin/env python
import boto3
import sys

def delete(session, user_name):
    user = session.resource('iam').User(user_name)
    try:
        [user.remove_group(GroupName = group.name) for group in user.groups.all()]
        [key.delete() for key in user.access_keys.all()]
        [user.detach_policy(policy.arn) for policy in user.attached_policies.all()]
        user.LoginProfile().delete()
        user.delete()
    except AttributeError:
        sys.stderr.write("User not found")

def add(session_bucket, user_name):
        iam = session.resource('iam')
        iam.create_user(UserName = user_name)
        iam.LoginProfile(user_name).create(Password='Password123',
                                        PasswordResetRequired=True)

try:
    command = sys.argv[1]
    user_name = sys.argv[2]
    session_bucket = []
    try:
        for profile in sys.argv[3:]:
            session = boto3.session.Session(profile_name = profile)
            if command == "add":
                add(session, user_name)
            elif command == "delete":
                delete(session, user_name)

    except IndexError:
        session_bucket.append(boto3.session.Session(profile_name = "default"))

except IndexError:
    print "Invalid arguments; iam_user {add|delete} username profiles (blank = default)"
